title: Swadhin
email: me@swadh.in
description: >- # this means to ignore newlines until "baseurl:"
  Some random collection of interesting stuffs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swadh.in"
twitter_username: swadhinbharat
github_username:  swadhinbharat
google_analytics: G-JTCFLHT968
# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: "jekyll/minima@1e8a445"
minima:
  # skin: dark
  date_format: "%b %-d, %Y"

  social_links:
    # - { platform: devto,          user_url: "https://dev.to/swadhin" }
    - { platform: facebook,       user_url: "https://www.facebook.com/swadhin" }
    - { platform: github,         user_url: "https://github.com/swadhinbharat" }
    - { platform: instagram,      user_url: "https://www.instagram.com/swadhin" }
    # - { platform: keybase,        user_url: "https://keybase.io/swadhin" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/swadhinpatel" }
    # - { platform: microdotblog,   user_url: "https://micro.blog/swadhin" }
    # - { platform: pinterest,      user_url: "https://in.pinterest.com/swadhin/" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/760901/swadhin" }
    # - { platform: telegram,       user_url: "https://t.me/swadhinbharat" }
    - { platform: twitter,        user_url: "https://twitter.com/swadhinbharat" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@swadhinbharat" }


  # # generate social links in footer
  # social_links:
  #   twitter: swadhinbharat
  #   github:  swadhinbharat
  #   # devto: jekyll
  #   # dribbble: jekyll
  #   facebook: swadhin
  #   # flickr:   jekyll
  #   instagram: swadhin
  #   linkedin: swadhinpatel
    # pinterest: jekyll
    # youtube: "@swadhinbharat"
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

header_pages:
  - _pages/blogs.md
  - _pages/collections.md
  - _pages/quotes.md
  - _pages/projects.md
  - _pages/about.md
  
include:
  - _pages

exclude:
  - .gitignore
  - docker-compose.yml
  - LICENSE
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/