title: Swadhin
email: me@swadh.in
description: >- # this means to ignore newlines until "baseurl:"
  Some random collection of interesting stuffs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swadh.in"
twitter_username: swadhinbharat
github_username:  swadhinbharat
google_analytics: G-JTCFLHT968
# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima
minima:
  # skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: swadhinbharat
    github:  swadhinbharat
    # devto: jekyll
    # dribbble: jekyll
    facebook: swadhin
    # flickr:   jekyll
    instagram: swadhin
    linkedin: swadhinpatel
    # pinterest: jekyll
    youtube: user/UCCziWX5AIA5fn9np7-IxxBA
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

header_pages:
  - blogs.md
  - quotes.md
  - projects.md
  - about.md

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
