title: Swadhin
email: me@swadh.in
description: >- # this means to ignore newlines until "baseurl:"
  Some random collection of interesting stuffs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swadh.in"
twitter_username: swadhinbharat
github_username:  swadhinbharat

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima
# minima:
#   skin: dark

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
