endpoints:

# Public services

  - name: vodafone
    group: external
    url: "https://vodafone.de/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1500"

# Internal services

  - name: transmission
    group: internal
    url: "http://raspberrypi.local:9091"
    interval: 5m
    conditions:
      - "[STATUS] == any(200, 401)"
      - "[RESPONSE_TIME] < 1000"

  - name: plex
    group: internal
    url: "http://raspberrypi.local:32400"
    interval: 5m
    conditions:
      - "[STATUS] == any(200, 401)"
      - "[RESPONSE_TIME] < 500"

  - name: rpi-monitor
    group: internal
    url: "http://raspberrypi.local:8888"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: ssh-raspberrypi
    group: internal
    url: "ssh://raspberrypi.local"
    ssh:
      username: ${RASPBERRYPI_USERNAME}
      password: ${RASPBERRYPI_PASSWORD}
    body: |
      {
        "command": "uptime"
      }
    interval: 5m
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] == 0"

# Website

  - name: check-domain-expiration
    group: website
    url: "https://swadh.in/"
    interval: 1h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

  - name: swadhin-dns-query-google-primary
    group: website
    url: "8.8.8.8" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "swadh.in"
      query-type: "A"
    conditions:
      - "[BODY] == any(185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153)"
      - "[DNS_RCODE] == NOERROR"

  - name: swadhin-dns-query-google-secondary
    group: website
    url: "8.8.4.4" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "swadh.in"
      query-type: "A"
    conditions:
      - "[BODY] == any(185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153)"
      - "[DNS_RCODE] == NOERROR"

  - name: swadhin-dns-query-cloudflare-primary
    group: website
    url: "1.1.1.1" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "swadh.in"
      query-type: "A"
    conditions:
      - "[BODY] == any(185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153)"
      - "[DNS_RCODE] == NOERROR"

  - name: swadhin-dns-query-cloudflare-secondary
    group: website
    url: "1.0.0.1" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "swadh.in"
      query-type: "A"
    conditions:
      - "[BODY] == any(185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153)"
      - "[DNS_RCODE] == NOERROR"

  - name: swadhin
    group: website
    url: "https://swadh.in"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1500"



  # - name: icmp-ping
  #   url: "icmp://example.org"
  #   interval: 1m
  #   conditions:
  #     - "[CONNECTED] == true"
